ALTER TABLE patchwork.room_members
    ADD COLUMN offline_ms bigint NOT NULL DEFAULT 0 CHECK (offline_ms >= 0);
CREATE TABLE patchwork.room_recovery (
    room_id uuid PRIMARY KEY REFERENCES patchwork.rooms,
    server_epoch uuid NOT NULL,
    last_tick uuid,
    budget0_ms bigint NOT NULL DEFAULT 0 CHECK (budget0_ms >= 0),
    budget1_ms bigint NOT NULL DEFAULT 0 CHECK (budget1_ms >= 0),
    both_offline_ms bigint NOT NULL DEFAULT 0 CHECK (both_offline_ms >= 0),
    recovering0 boolean NOT NULL DEFAULT false,
    recovering1 boolean NOT NULL DEFAULT false,
    restart_remaining_ms bigint NOT NULL DEFAULT 0 CHECK (restart_remaining_ms >= 0)
);
-- A lifecycle event is generated by the server, not by a player.
ALTER TABLE patchwork.game_events ALTER COLUMN user_id DROP NOT NULL;
