//! Frozen 2026-09-13 from src/new_game/patches.rs::new_patches.
//! IDs were assigned once in legacy order (one-based); lookup never uses that order.
//! Legacy bt.0 -> button_cost, bt.1 -> time_cost, button -> income.
use super::{PATCH_COUNT, PatchDefinition, PatchId};

pub const PATCHES: [PatchDefinition; PATCH_COUNT] = [
    PatchDefinition {
        id: PatchId(1),
        cells: &[(0, 0), (1, 0), (1, 1), (1, 2), (1, 3), (2, 3)],
        button_cost: 1,
        time_cost: 2,
        income: 0,
    },
    PatchDefinition {
        id: PatchId(2),
        cells: &[(1, 0), (0, 1), (1, 1), (2, 1), (1, 2), (1, 3)],
        button_cost: 0,
        time_cost: 3,
        income: 1,
    },
    PatchDefinition {
        id: PatchId(3),
        cells: &[(2, 0), (1, 1), (2, 1), (0, 2), (1, 2)],
        button_cost: 10,
        time_cost: 4,
        income: 3,
    },
    PatchDefinition {
        id: PatchId(4),
        cells: &[(0, 0), (0, 1), (1, 1), (0, 2), (0, 3)],
        button_cost: 3,
        time_cost: 4,
        income: 1,
    },
    PatchDefinition {
        id: PatchId(5),
        cells: &[(0, 0), (1, 0), (1, 1)],
        button_cost: 3,
        time_cost: 1,
        income: 1,
    },
    PatchDefinition {
        id: PatchId(6),
        cells: &[(0, 0), (1, 0), (2, 0), (1, 1), (0, 2), (1, 2), (2, 2)],
        button_cost: 2,
        time_cost: 3,
        income: 0,
    },
    PatchDefinition {
        id: PatchId(7),
        cells: &[(1, 0), (0, 1), (1, 1), (0, 2), (1, 2), (0, 3)],
        button_cost: 4,
        time_cost: 2,
        income: 0,
    },
    PatchDefinition {
        id: PatchId(8),
        cells: &[(0, 0), (1, 0), (2, 0), (0, 1), (1, 1)],
        button_cost: 2,
        time_cost: 2,
        income: 0,
    },
    PatchDefinition {
        id: PatchId(9),
        cells: &[(1, 0), (2, 0), (0, 1), (1, 1), (1, 2), (2, 2)],
        button_cost: 3,
        time_cost: 6,
        income: 0,
    },
    PatchDefinition {
        id: PatchId(10),
        cells: &[(0, 0), (1, 0)],
        button_cost: 2,
        time_cost: 1,
        income: 0,
    },
    PatchDefinition {
        id: PatchId(11),
        cells: &[(0, 0), (1, 0), (0, 1), (0, 2), (0, 3)],
        button_cost: 10,
        time_cost: 3,
        income: 2,
    },
    PatchDefinition {
        id: PatchId(12),
        cells: &[(1, 0), (0, 1), (1, 1), (2, 1), (1, 2)],
        button_cost: 5,
        time_cost: 4,
        income: 2,
    },
    PatchDefinition {
        id: PatchId(13),
        cells: &[(0, 0), (1, 0), (2, 0), (1, 1), (1, 2), (1, 3)],
        button_cost: 7,
        time_cost: 2,
        income: 2,
    },
    PatchDefinition {
        id: PatchId(14),
        cells: &[(1, 0), (0, 1), (1, 1), (1, 2), (2, 2), (1, 3)],
        button_cost: 2,
        time_cost: 1,
        income: 0,
    },
    PatchDefinition {
        id: PatchId(15),
        cells: &[(0, 0), (1, 0), (0, 1), (1, 1), (2, 1), (2, 2)],
        button_cost: 8,
        time_cost: 6,
        income: 3,
    },
    PatchDefinition {
        id: PatchId(16),
        cells: &[(0, 0), (0, 1), (1, 1), (0, 2), (1, 2), (0, 3)],
        button_cost: 7,
        time_cost: 4,
        income: 2,
    },
    PatchDefinition {
        id: PatchId(17),
        cells: &[(0, 0), (1, 0), (1, 1), (1, 2)],
        button_cost: 4,
        time_cost: 6,
        income: 2,
    },
    PatchDefinition {
        id: PatchId(18),
        cells: &[(1, 0), (1, 1), (0, 2), (1, 2), (2, 2), (1, 3), (1, 4)],
        button_cost: 1,
        time_cost: 4,
        income: 1,
    },
    PatchDefinition {
        id: PatchId(19),
        cells: &[(0, 0), (1, 0), (1, 1), (1, 2), (0, 3), (1, 3)],
        button_cost: 1,
        time_cost: 5,
        income: 1,
    },
    PatchDefinition {
        id: PatchId(20),
        cells: &[(0, 0), (1, 0), (1, 1)],
        button_cost: 1,
        time_cost: 3,
        income: 0,
    },
    PatchDefinition {
        id: PatchId(21),
        cells: &[(0, 0), (0, 1), (0, 2), (0, 3)],
        button_cost: 3,
        time_cost: 3,
        income: 1,
    },
    PatchDefinition {
        id: PatchId(22),
        cells: &[(0, 0), (0, 1), (0, 2), (1, 2), (1, 3)],
        button_cost: 2,
        time_cost: 3,
        income: 1,
    },
    PatchDefinition {
        id: PatchId(23),
        cells: &[(1, 0), (2, 0), (0, 1), (1, 1)],
        button_cost: 3,
        time_cost: 2,
        income: 1,
    },
    PatchDefinition {
        id: PatchId(24),
        cells: &[(0, 0), (1, 0), (2, 0), (0, 1)],
        button_cost: 4,
        time_cost: 2,
        income: 1,
    },
    PatchDefinition {
        id: PatchId(25),
        cells: &[(0, 0), (1, 0), (2, 0), (0, 1), (2, 1)],
        button_cost: 1,
        time_cost: 2,
        income: 0,
    },
    PatchDefinition {
        id: PatchId(26),
        cells: &[(0, 0), (1, 0), (1, 1), (2, 1)],
        button_cost: 7,
        time_cost: 6,
        income: 3,
    },
    PatchDefinition {
        id: PatchId(27),
        cells: &[
            (1, 0),
            (0, 1),
            (1, 1),
            (2, 1),
            (0, 2),
            (1, 2),
            (2, 2),
            (1, 3),
        ],
        button_cost: 5,
        time_cost: 3,
        income: 1,
    },
    PatchDefinition {
        id: PatchId(28),
        cells: &[(0, 0), (1, 0), (0, 1), (1, 1), (0, 2), (0, 3)],
        button_cost: 10,
        time_cost: 5,
        income: 3,
    },
    PatchDefinition {
        id: PatchId(29),
        cells: &[(0, 0), (0, 1), (1, 1), (2, 1), (0, 2)],
        button_cost: 5,
        time_cost: 5,
        income: 2,
    },
    PatchDefinition {
        id: PatchId(30),
        cells: &[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4)],
        button_cost: 7,
        time_cost: 1,
        income: 1,
    },
    PatchDefinition {
        id: PatchId(31),
        cells: &[(0, 0), (1, 0), (2, 0), (1, 1)],
        button_cost: 2,
        time_cost: 2,
        income: 0,
    },
    PatchDefinition {
        id: PatchId(32),
        cells: &[(0, 0), (1, 0), (0, 1), (1, 1)],
        button_cost: 6,
        time_cost: 5,
        income: 2,
    },
    PatchDefinition {
        id: PatchId(33),
        cells: &[(0, 0), (1, 0), (2, 0)],
        button_cost: 2,
        time_cost: 2,
        income: 0,
    },
];
